# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
